- name: Ensure splunk_admins group exists
  group:
    name: splunk_admins
    state: present
  when: "'splunk' in group_names"

- name: Check if each splunk user exists
  command: "getent passwd {{ item }}"
  register: passwd_check
  ignore_errors: yes
  changed_when: false
  loop: "{{ splunk_admins }}"
  when: "'splunk' in group_names"

- name: Add existing splunk users to splunk_admins group
  user:
    name: "{{ item.item }}"
    groups: splunk_admins
    append: yes
  loop: "{{ passwd_check.results | selectattr('rc', 'equalto', 0) | list }}"
  when: "'splunk' in group_names"

- name: Configure sudo access for splunk_admins
  copy:
    src: sudo-splunk_admins
    dest: /etc/sudoers.d/sudo-splunk_admins
    mode: '0440'
  when: "'splunk' in group_names"

