---
- name: Ensure splunk group(s) exist
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ splunk_admins }}"
  when: "'splunk' in group_names"

- name: Ensure splunk user(s) exist
  user:
    name: "{{ item }}"
    group: splunk_admins
    state: present
  loop: "{{ splunk_admins }}"
  when: "'splunk' in group_names"

- name: Configure sudo access for splunk_admins
  copy:
    src: sudo-splunk_admins
    dest: /etc/sudoers.d/sudo-splunk_admins
    mode: '0440'
  when: "'splunk' in group_names"
