- name: Ensure kafka_admins group exists
  group:
    name: kafka_admins
    state: present
  when: "'kafka' in group_names"

- name: Check if each kafka user exists
  command: "getent passwd {{ item }}"
  register: passwd_check
  ignore_errors: yes
  changed_when: false
  loop: "{{ kafka_admins }}"
  when: "'kafka' in group_names"

- name: Add existing kafka users to kafka_admins group
  user:
    name: "{{ item.item }}"
    groups: kafka_admins
    append: yes
  loop: "{{ passwd_check.results | selectattr('rc', 'equalto', 0) | list }}"
  when: "'kafka' in group_names"

- name: Configure sudo access for kafka_admins
  copy:
    src: sudo-kafka_admins
    dest: /etc/sudoers.d/sudo-kafka_admins
    mode: '0440'
  when: "'kafka' in group_names"

